### PR TITLE
10840 Stock Tickers Formatted for Existing index.html File

### PR DESCRIPTION
**Pull request by REPNOT**
The following HTML file has been preformatted to be copied into the existing index.html file located in the static directory.  This block of html contains 10840 stock tickers .  Please feel free to use if it will be of any help.  If updates are needed, please let me know and I'm more than happy to run the script and send new data.

### CODE REVIEW

**Comment by vk-playground** [comment]
@REPNOT Hey Derek, I missed the request til now. Your html of 10840 stock tickers is more comprehensive for sure! Thank you for sharing!😍 Since this is a demo project and it might be easier to let the web scraper to scrape the recent news of top 500 companies in this code logic, the original html might be a better fit in this case.

**Comment by vk-playground** [comment]
We can work on other more comprehensive project tho!

**Comment by REPNOT** [comment]
Hello.  You're welcome, it was no trouble at all.  I just wanted to return the favor for the CSS tip covered in the Streamlit Blog. So thank you for sharing.

I actually converted the stock tickers from a string format to HTML.  The list was already stored in a JSON format, so one loop took care of it.  The HTML mirrors the structure used for the drop down menu in your index.html file.  It can be pasted right over the existing menu options.

I have a new list that is smaller and should be of better quality than the original, if it would be helpful at all.

**Comment by REPNOT** [comment]
> We can work on other more comprehensive project tho!

That sounds good.  Feel free to contact me anytime.  I appreciate you responding back.

**Pull request closed without merging**
